# This file was *autogenerated* from the file animation.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20)
g = Graphics()
g.axes(False)
g += line([(_sage_const_0 ,_sage_const_0 ), [_sage_const_1 ,_sage_const_1 ], (_sage_const_0 ,_sage_const_1 )])
g1 = Graphics()
c = circle((_sage_const_1 ,_sage_const_1 ), _sage_const_1 , rgbcolor=(_sage_const_1 ,_sage_const_0 ,_sage_const_0 ))
g1 += c
type(g+c)
type(c)
a = animate([g,g1,g,g1,g+g1,g,g1])
a.show(delay=_sage_const_20 )
